// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqphlzqactfvaiuoahcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGhsenFhY3RmdmFpdW9haGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODY2MDMsImV4cCI6MjA2Mjk2MjYwM30.NjXBNOXgoJ-3jOm6Yti4iJ36JqRjAPI66fp5wZtsUeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});